a = int(input("Enter first number:"))
b = int(input("Enter second number:"))
print("Addtion:",a+b)
print("sub:",a-b)
print("multiplication:",a*b)
print("division:",a/b)
print("modules:",a%b)
print("FD:",a//b)
print("power:",a**b)